---
title: 'Tidy Data'
subtitle: Scraping Data
output:
  pdf_document:
    fig_height: 3
    fig_width: 4.5
  html_document: default
word_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```


# Past Winners (2010-2020)
```{r}
robotstxt::paths_allowed("https://totalmusicawards.com/grammy-awards/record-of-the-year-winners-nominees-archive/")
```

```{r}
past_winners_record <- read_html("https://totalmusicawards.com/grammy-awards/record-of-the-year-winners-nominees-archive/")
past_winners_album <- read_html("https://totalmusicawards.com/grammy-awards/album-of-the-year-winners-nominees-archive//")
past_winners_song <- read_html("https://totalmusicawards.com/grammy-awards/song-of-the-year-winners-nominees-archive/")
past_winners_artist <- read_html("https://totalmusicawards.com/grammy-awards/best-new-artist-winners-nominees-archive/")

record_winners <- html_elements(past_winners_record, "p:nth-child(12) strong , p:nth-child(13) strong , p:nth-child(14) strong , p:nth-child(15) strong , p:nth-child(16) strong , p:nth-child(17) strong , p:nth-child(18) strong , p:nth-child(19) strong , p:nth-child(20) strong , p:nth-child(21) strong , p:nth-child(22) strong")
record_winners

album_winners <- html_elements(past_winners_album, "p:nth-child(15) strong , p:nth-child(12) strong , p:nth-child(13) strong , p:nth-child(19) strong , p:nth-child(14) strong , p:nth-child(16) strong , p:nth-child(17) strong , p:nth-child(20) strong , p:nth-child(18) strong , p:nth-child(21) strong , p:nth-child(22) strong")
album_winners

song_winners <- html_elements(past_winners_song, "p:nth-child(11) strong , p:nth-child(12) strong , p:nth-child(13) strong , p:nth-child(14) strong , p:nth-child(15) strong , p:nth-child(16) strong , p:nth-child(17) strong , p:nth-child(18) strong , p:nth-child(19) strong , p:nth-child(20) strong , p:nth-child(21) strong")
song_winners 

new_artist_winners <- html_elements(past_winners_artist, "p:nth-child(6) strong , p:nth-child(7) strong , p:nth-child(8) strong , p:nth-child(9) strong , p:nth-child(10) strong , p:nth-child(11) strong , p:nth-child(12) strong , p:nth-child(13) strong , p:nth-child(14) strong , p:nth-child(15) strong , p:nth-child(16) strong")
new_artist_winners
```

```{r}
record_name_of_song <- record_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_extract_all("^(.)*,") %>%
  str_replace(",", "")

record_artist <- record_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_extract_all(", (.)*$") %>%
  str_replace(", ", "") %>%
  str_replace_all(" featuring(.)*$", "")

record <- as_tibble(cbind(category = rep("Record of the Year", 11), title = record_name_of_song, artist = record_artist)) %>%
  mutate(year = c(2020:2010)) %>%
  select(year, category, title, artist)
```

```{r}
album_name_of_album <- album_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_extract_all("^(.)*,") %>%
  str_replace(",$", "")

album_artist <- album_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_replace_all("(.)+,", "") %>%
  str_replace("^ ", "") %>%
  str_replace("amp;", "") %>%
  str_replace_all(" featuring(.)*$", "")

album <- as_tibble(cbind(category = rep("Album of the Year", 11), title = album_name_of_album, artist = album_artist)) %>%
  mutate(year = c(2020:2010)) %>%
  select(year, category, title, artist)
print(album, width = Inf)
```

```{r}
song_name_of_song <- song_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_extract("^[^,]*,") %>%
  str_replace("^ ", "") %>%
  str_replace(",", "")

song_artist <- song_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_extract_all(", (.)*$") %>%
  str_replace(", ", "") %>%
  str_extract("\\((.)*\\)") %>%
  str_replace("\\(", "") %>%
  str_replace("\\)", "")

song <- as_tibble(cbind(category = rep("Song of the Year", 11), title = song_name_of_song, artist = song_artist)) %>%
  mutate(year = c(2020:2010)) %>%
  select(year, category, title, artist)

print(song, width = Inf)
```

```{r}
new_artist <- new_artist_winners %>%
  str_replace_all("<[/]{0,1}strong>", "") %>%
  str_extract_all(" (.)*$") %>%
  str_replace("^ ", "") %>%
  str_replace(" &(.)*$", "")

artist <- as_tibble(cbind(category = rep("Best New Artist of the Year", 11), artist = new_artist)) %>%
  mutate(year = c(2020:2010),
         title = c("NA")) %>%
  select(year, category, title, artist)
```

```{r}
tibble <- rbind(record, album, song, artist)

print(tibble, n = Inf, width = Inf)
```





